# Generated by Django 3.0 on 2021-01-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblemodel',
            name='goodtext',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biblemodel',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
